stages:
  - stage: build
    displayName: 'Build Stage'
    jobs:
      - job: build
        displayName: 'Build Job'
        steps:
          - task: Maven@4
            displayName: 'Run Maven Build'
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'clean package'
              publishJUnitResults: false
              javaHomeOption: 'JDKVersion'
              mavenVersionOption: 'Default'
      
      - job: copy
        displayName: 'Copy Job'
        dependsOn: build
        steps:
          - task: CopyFiles@2
            displayName: 'Copy WAR Files'
            inputs:
              SourceFolder: '$(System.DefaultWorkingDirectory)/target'
              Contents: '**/*.war'
              TargetFolder: '$(Build.ArtifactStagingDirectory)'
      
      - job: publish
        displayName: 'Publish Job'
        dependsOn: copy
        steps:
          - task: PublishBuildArtifacts@1
            displayName: 'Publish Artifacts'
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'drop'
              publishLocation: 'Container'
