trigger:
- master
pool:
  vmimage: ubuntu-latest
stages:
  - stage: build
    displayName: build
    jobs:
    - job: build
      displayName: build
      steps:
        - task: Maven@4
          inputs:
            mavenPomFile: 'pom.xml'
            publishJUnitResults: false
            javaHomeOption: 'JDKVersion'
            mavenVersionOption: 'Default'
            mavenAuthenticateFeed: false
            effectivePomSkip: false
            sonarQubeRunAnalysis: false
            goals: package
        
        - task: CopyFiles@2
          inputs:
            SourceFolder: '$(agent.builddirectory)'
            Contents: '**/*.war'
            TargetFolder: '$(build.artifactstagingdirectory)'
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'drop'
            publishLocation: 'Container'
  - stage: Release
    displayName: Release
    jobs:
    - deployment: 
      environment: dev
      strategy:
       runOnce:
         deploy:
           steps:
             - task: AzureRmWebAppDeployment@4
               inputs:
                 ConnectionType: 'AzureRM'
                 azureSubscription: 'Free Trial(98391885-1dc7-4963-93d0-7590a267b3f7)'
                 appType: 'webAppLinux'
                 WebAppName: 'web000'
                 packageForLinux: '$(Pipeline.Workspace)/**/*.war'
  

      

   