trigger:
- main

pool:
  vmImage: ubuntu-latest
parameters:
  - name: buildConfiguration
    type: string
    default: 'Release'
    displayName: 'Build Configuration'
  
jobs:
- job: Build
  displayName: "Build Job"
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: |
      echo "Building with configuration: ${{ parameters.buildConfiguration }}"      
    displayName: "Print Build Configuration"
