stages:
  - stage: build
    displayName: 'Build Stage'
    jobs:
      - job: build
        displayName: 'Build Job'
        steps:
          - task: Maven@4
            displayName: 'Run Maven Build'
            inputs:
              mavenPomFile: 'pom.xml'
              publishJUnitResults: false
              javaHomeOption: 'JDKVersion'
              mavenVersionOption: 'Default'
              mavenAuthenticateFeed: false
              effectivePomSkip: false
              sonarQubeRunAnalysis: false
              goals: package
      
      - job: copy
        displayName: 'Copy '
        dependsOn: build  # Ensures 'copy' runs only after 'build' completes
        steps:
          - task: CopyFiles@2
            displayName: 'Copy WAR Files'
            inputs:
              SourceFolder: '$(System.DefaultWorkingDirectory)'
              Contents: '**/*.war'
              TargetFolder: '$(Build.ArtifactStagingDirectory)'
      
      - job: publish
        displayName: 'Publish Job'
        dependsOn: copy  # Ensures 'publish' runs only after 'copy' completes
        steps:
          - task: PublishBuildArtifacts@1
            displayName: 'Publish Artifacts'
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'drop'
              publishLocation: 'Container'
